name: HashiCorp Packer
on: pull_request

jobs:
  build:
    name: Packer Build
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@master
    - uses: ./action-a
      env:
        MY_NAME: "Nishkarsh Raj"
